
package com.example.demo.test.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "JwsServiceHello", targetNamespace = "http://service.test.demo.example.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface JwsServiceHello {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getValue", targetNamespace = "http://service.test.demo.example.com/", className = "com.example.demo.test.client.GetValue")
    @ResponseWrapper(localName = "getValueResponse", targetNamespace = "http://service.test.demo.example.com/", className = "com.example.demo.test.client.GetValueResponse")
    @Action(input = "http://service.test.demo.example.com/JwsServiceHello/getValueRequest", output = "http://service.test.demo.example.com/JwsServiceHello/getValueResponse")
    public String getValue(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNum", targetNamespace = "http://service.test.demo.example.com/", className = "com.example.demo.test.client.GetNum")
    @ResponseWrapper(localName = "getNumResponse", targetNamespace = "http://service.test.demo.example.com/", className = "com.example.demo.test.client.GetNumResponse")
    @Action(input = "http://service.test.demo.example.com/JwsServiceHello/getNumRequest", output = "http://service.test.demo.example.com/JwsServiceHello/getNumResponse")
    public int getNum(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
